[package]
name = "persistence"
version = "0.1.0"
edition = "2024"

[dependencies]
influxdb = "0.6.0"
tokio = { version = "1", features = ["full"] }
domain = { path = "../domain" }
async-trait = "0.1.80"
chrono = { version = "0.4", features = ["serde"] }
