name: bydmate

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: byd_mate
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configuration/postgres/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql

  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: byd_org
      DOCKER_INFLUXDB_INIT_BUCKET: byd_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-token
    volumes:
      - influx_data:/var/lib/influxdb2

  emqx:
    image: emqx/emqx:5.10.0
    restart: always
    ports:
      - "1883:1883" # MQTT TCP
      - "8083:8083" # MQTT WebSocket
      - "8084:8084" # REST API
      - "18083:18083" # Dashboard
    environment:
      EMQX_NODE__NAME: emqx@127.0.0.1
      EMQX_DASHBOARD__LISTENERS__HTTP__BIND: 0.0.0.0:18083
      EMQX_LISTENERS__TCP__DEFAULT__BIND: 0.0.0.0:1883
      EMQX_LISTENERS__WS__DEFAULT__BIND: 0.0.0.0:8083
      EMQX_REST__LISTENERS__HTTP__BIND: 0.0.0.0:8084
    volumes: []

  mqtt_subscriber:
    build:
      context: ../backend/mqtt_subscriber
      dockerfile: Dockerfile
    restart: always
    environment:
      MQTT_BROKER: emqx:1883
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: my-super-secret-token
      INFLUXDB_ORG: byd_org
      INFLUXDB_BUCKET: byd_bucket
    depends_on:
      - emqx
      - influxdb

  data_analyzer:
    build:
      context: ../backend/data_analyzer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081" # API Port
    environment:
      MQTT_BROKER: emqx:1883
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: my-super-secret-token
      INFLUXDB_ORG: byd_org
      INFLUXDB_BUCKET: byd_bucket
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: user
      PG_PASSWORD: password
      PG_DBNAME: byd_mate
    depends_on:
      - emqx
      - influxdb
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always

volumes:
  influx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/influx
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  configuration:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./configuration